version: 2
updates:

  # -- github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # -- node
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
        - "*"
        exclude-patterns:
        # FIXME: currently fails due to incompatibility with react:
        # https://github.com/facebook/create-react-app/issues/13080#issue-1635236109
        - "typescript"
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]


  # -- poetry
  - package-ecosystem: "pip"
    directory: "/docat"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        patterns:
        - "*"
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]

  # -- docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
